version: '3.5'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: middleearthmedia/newlaravel
    networks:
     - appnet
    volumes:
     - ./:/var/www/html
    ports:
     - 80:80
    container_name: newlaravel
networks:
  appnet:
    driver: bridge
